### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 1074: illegal multibyte sequence

### ISSUE THREAD

**Issue by lightspread** [Pullusb/snippetsLibrary#3]
my local language is zh-cn so this addon raise decode error after install . It' work after change 
func.py line 53:
with open(fp, 'r',encoding='utf-8') as fd:

thanks for Pullusb's wonder work!

**Comment by Pullusb** [comment]
I modified the line to read with the correct encoding, thank for your contribution
