### ISSUE TITLE
The keybind Ctrl+t unfortunately doesn't work on Blender 3.0

### ISSUE THREAD

**Issue by codingforpleasure** [Pullusb/snippetsLibrary#8]
I have installed this super nice addon on Blender 3.0,
and I have followed the repo's instructions:
"(A new Snippets tab will be in the text editor's toolbar (accessible with ctrl + T))"

but unfortunately the keybind was taken in Blender's Keymap -> Text ->Text Generic -> "Context Toggle" (Ctrl+T)
So I have disabled it and tried to invoke the snippet toolbox but sadly it doesn't appear.

Any suggestion how can I fix this issue? am I missing something?
**Thank you for the great efforts putting into developing this Addon**

**Comment by Pullusb** [comment]
Hi !
The `Ctrl+T`  I mention to display sidebar IS the `Context Toggle` and it works as expected in all version of blender.
This is just the native shortcut to toggle the sidebar (True that i said "toolbar" in my doc).
You can also clic on the super tiny `+` icon on the upper right side of the text editor area to toggle it.

Snippet's library doesn't add shortcuts. You do not have to invoke it, it's just there in text editor.

Cheers

**Comment by codingforpleasure** [comment]
Thank you for the help, my mistake! :)
